[build]
  publish = "public"
  command = "hugo --gc --minify -d public;"

[build.environment]
  HUGO_VERSION = "0.161.0"
  NODE_VERSION = "24.15.0"

[context.branch-deploy]
  command = "hugo --gc --minify -d public -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"